language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - PHPUNIT_VERSION=~4.0

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: trusty
    - php: 7.2
      env: PHPUNIT_VERSION=~6.0
    - php: 7.3
      env: PHPUNIT_VERSION=~6.0

cache:
  directories:
    - $HOME/.composer

before_install:
  - composer self-update
  - composer clear-cache
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install:
  composer update --no-interaction --no-ansi --optimize-autoloader --prefer-dist

script:
  - php vendor/bin/phpunit

# after_success:
#   - travis_retry php vendor/bin/php-coveralls
